In [1]:
import pandas as pd
import numpy as np
np.random.seed(7)

data = np.random.randint(1,50,16,).reshape((4,4))
index = ['Year '+str(i) for i in range(1,5)]
columns = ['Brand '+chr(65+i) for i in range(4)]
df = pd.DataFrame(data, columns = columns, index= index )
df

Brand A  Brand B  Brand C  Brand D
Year 1       48        5       26        4
Year 2       20       24       40       29
Year 3       15       24        9       26
Year 4       47       43       27        9

## access the following attributes: columns, index, shape, and values

In [2]:
print(df.columns)
print(df.index)
print(df.shape)
print(df.values)

Index(['Brand A', 'Brand B', 'Brand C', 'Brand D'], dtype='object')
Index(['Year 1', 'Year 2', 'Year 3', 'Year 4'], dtype='object')
(4, 4)
[[48  5 26  4]
 [20 24 40 29]
 [15 24  9 26]
 [47 43 27  9]]


## select the 'Brand A' and 'Brand C' columns, individually

In [3]:
print(df['Brand A'])
print(df['Brand C'])

Year 1    48
Year 2    20
Year 3    15
Year 4    47
Name: Brand A, dtype: int64
Year 1    26
Year 2    40
Year 3     9
Year 4    27
Name: Brand C, dtype: int64


## show the descriptive statistics for each column with the describe () function

In [4]:
df.describe()

Brand A    Brand B    Brand C    Brand D
count   4.000000   4.000000   4.000000   4.000000
mean   32.500000  24.000000  25.500000  17.000000
std    17.445152  15.513435  12.714821  12.355835
min    15.000000   5.000000   9.000000   4.000000
25%    18.750000  19.250000  21.750000   7.750000
50%    33.500000  24.000000  26.500000  17.500000
75%    47.250000  28.750000  30.250000  26.750000
max    48.000000  43.000000  40.000000  29.000000

## show information from the dataset with the info () function

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Year 1 to Year 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand A  4 non-null      int64
 1   Brand B  4 non-null      int64
 2   Brand C  4 non-null      int64
 3   Brand D  4 non-null      int64
dtypes: int64(4)
memory usage: 320.0+ bytes


## show the data type of each column in the dataset

In [6]:
df.dtypes

Brand A    int64
Brand B    int64
Brand C    int64
Brand D    int64
dtype: object

## convert the data type of the columns to float

In [7]:
df = df.astype(float)
df.dtypes

Brand A    float64
Brand B    float64
Brand C    float64
Brand D    float64
dtype: object

## select the profit of the brands in year 1 (use the loc and iloc functions)

In [10]:
print(df.loc['Year 1'])
df.iloc[0:1, :]

Brand A    48.0
Brand B     5.0
Brand C    26.0
Brand D     4.0
Name: Year 1, dtype: float64


Brand A  Brand B  Brand C  Brand D
Year 1     48.0      5.0     26.0      4.0

## select the profit for Brand C in years 1 and 3 (use the loc and iloc functions)

In [12]:
print(df.loc[['Year 1', 'Year 3'], 'Brand C'])
df.iloc[[0, 2], 2:3]


Year 1    26.0
Year 3     9.0
Name: Brand C, dtype: float64


Brand C
Year 1     26.0
Year 3      9.0

## select the profit for brands A, C, and D, in years 2 and 4 (use the loc and iloc functions)

In [13]:
print(df.loc[['Year 2', 'Year 4'], ['Brand A', 'Brand C', 'Brand D']])
df.iloc[[1, 3], [0, 2, 3]]


        Brand A  Brand C  Brand D
Year 2     20.0     40.0     29.0
Year 4     47.0     27.0      9.0


Brand A  Brand C  Brand D
Year 2     20.0     40.0     29.0
Year 4     47.0     27.0      9.0

## show the average profit of each brand in this time interval

In [14]:
df.mean()

Brand A    32.5
Brand B    24.0
Brand C    25.5
Brand D    17.0
dtype: float64

## show the average profit for all brands in each year

In [15]:
df.mean(axis=1)

Year 1    20.75
Year 2    28.25
Year 3    18.50
Year 4    31.50
dtype: float64